### ISSUE TITLE
Running `npm run dev` produces error for me

### ISSUE THREAD

**Issue by jeremiah** [looselytyped/web-apps-with-vue3#1]
```
21:58 jeremiah@skull:/srv/html/vue/oreilly-SPA/web-apps-with-vue3 $ (main) npm run dev

> friends-hq@0.0.0 dev
> vite

file:///srv/html/vue/oreilly-SPA/web-apps-with-vue3/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
npm ERR! code 1
npm ERR! path /srv/html/vue/oreilly-SPA/web-apps-with-vue3
npm ERR! command failed
npm ERR! command sh -c vite

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jeremiah/.npm/_logs/2023-01-26T02_58_45_567Z-debug.log
```
Here's the log;
```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
1 info using npm@7.5.2
2 info using node@v12.22.12
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/srv/html/vue/oreilly-SPA/web-apps-with-vue3/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/home/jeremiah/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 6ms
19 verbose npm-session 809bed4f9610a580
20 timing npm:load Completed in 13ms
21 timing command:run-script Completed in 76ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:314:20)
22 verbose stack     at maybeClose (internal/child_process.js:1022:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
23 verbose pkgid friends-hq@0.0.0
24 verbose cwd /srv/html/vue/oreilly-SPA/web-apps-with-vue3
25 verbose Linux 5.10.0-21-amd64
26 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
27 verbose node v12.22.12
28 verbose npm  v7.5.2
29 error code 1
30 error path /srv/html/vue/oreilly-SPA/web-apps-with-vue3
31 error command failed
32 error command sh -c vite
33 verbose exit 1
```
This appears to me that I need to install vite, but that brings a TON of npm WARN EBADENGINE errors.

**Comment by jeremiah** [comment]
I run Debian and Debian Stable has an old version of node; 12.22.12. I updated the version of node and npm and everything works.
